# Generated by Django 5.0.6 on 2024-06-04 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletteredition',
            name='content',
        ),
        migrations.CreateModel(
            name='HeadingBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('type', models.CharField(default='heading block', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heading_blocks', to='newsletter.newsletteredition')),
            ],
        ),
        migrations.CreateModel(
            name='ImageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='newsletters/images/%Y/%m/%d/')),
                ('caption', models.CharField(blank=True, max_length=1500)),
                ('type', models.CharField(default='image block', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_blocks', to='newsletter.newsletteredition')),
            ],
        ),
        migrations.CreateModel(
            name='TextBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('type', models.CharField(default='text block', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_blocks', to='newsletter.newsletteredition')),
            ],
        ),
    ]
