# Generated by Django 4.2.7 on 2024-06-04 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_made_title_field_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_picture_url',
            field=models.CharField(max_length=2083),
        ),
    ]
